### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by bitbegin** [EvgeniyPeshkov/syntax-highlighter#45]
```
npm install --target=6.1.2 --runtime=electron --disturl=https://atom.io/download/electron

> syntax-highlighter@0.4.2 postinstall /Users/bitbegin/Desktop/syntax-highlighter
> node ./scripts/build.js

Compiling c parser
Compiling cpp parser
Compiling go parser
Compiling javascript parser
Compiling lua parser
Compiling php parser
Compiling python parser
Compiling ruby parser
Compiling rust parser
Compiling shellscript parser
Compiling typescript parser
Compiling typescriptreact parser
Failed to build wasm for ruby: Command failed: node_modules/.bin/tree-sitter build-wasm node_modules/tree-sitter-ruby
events.js:298
      throw er; // Unhandled 'error' event
      ^

Error: spawn /Users/bitbegin/Desktop/syntax-highlighter/node_modules/tree-sitter-cli/tree-sitter EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -13,
  code: 'EACCES',
  syscall: 'spawn /Users/bitbegin/Desktop/syntax-highlighter/node_modules/tree-sitter-cli/tree-sitter',
  path: '/Users/bitbegin/Desktop/syntax-highlighter/node_modules/tree-sitter-cli/tree-sitter',
  spawnargs: [ 'build-wasm', 'node_modules/tree-sitter-ruby' ]
}

Failed to build wasm for python: Command failed: node_modules/.bin/tree-sitter build-wasm node_modules/tree-sitter-python
events.js:298
      throw er; // Unhandled 'error' event
      ^

Error: spawn /Users/bitbegin/Desktop/syntax-highlighter/node_modules/tree-sitter-cli/tree-sitter EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -13,
  code: 'EACCES',
  syscall: 'spawn /Users/bitbegin/Desktop/syntax-highlighter/node_modules/tree-sitter-cli/tree-sitter',
  path: '/Users/bitbegin/Desktop/syntax-highlighter/node_modules/tree-sitter-cli/tree-sitter',
  spawnargs: [ 'build-wasm', 'node_modules/tree-sitter-python' ]
}

Failed to build wasm for lua: Command failed: node_modules/.bin/tree-sitter build-wasm node_modules/tree-sitter-lua
events.js:298
      throw er; // Unhandled 'error' event
      ^

Error: spawn /Users/bitbegin/Desktop/syntax-highlighter/node_modules/tree-sitter-cli/tree-sitter EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -13,
  code: 'EACCES',
  syscall: 'spawn /Users/bitbegin/Desktop/syntax-highlighter/node_modules/tree-sitter-cli/tree-sitter',
  path: '/Users/bitbegin/Desktop/syntax-highlighter/node_modules/tree-sitter-cli/tree-sitter',
  spawnargs: [ 'build-wasm', 'node_modules/tree-sitter-lua' ]
}

Failed to build wasm for javascript: Command failed: node_modules/.bin/tree-sitter build-wasm node_modules/tree-sitter-javascript
events.js:298
      throw er; // Unhandled 'error' event
      ^

Error: spawn /Users/bitbegin/Desktop/syntax-highlighter/node_modules/tree-sitter-cli/tree-sitter EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -13,
  code: 'EACCES',
  syscall: 'spawn /Users/bitbegin/Desktop/syntax-highlighter/node_modules/tree-sitter-cli/tree-sitter',
  path: '/Users/bitbegin/Desktop/syntax-highlighter/node_modules/tree-sitter-cli/tree-sitter',
  spawnargs: [ 'build-wasm', 'node_modules/tree-sitter-javascript' ]
}

Failed to build wasm for go: Command failed: node_modules/.bin/tree-sitter build-wasm node_modules/tree-sitter-go
events.js:298
      throw er; // Unhandled 'error' event
      ^

Error: spawn /Users/bitbegin/Desktop/syntax-highlighter/node_modules/tree-sitter-cli/tree-sitter EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -13,
  code: 'EACCES',
  syscall: 'spawn /Users/bitbegin/Desktop/syntax-highlighter/node_modules/tree-sitter-cli/tree-sitter',
  path: '/Users/bitbegin/Desktop/syntax-highlighter/node_modules/tree-sitter-cli/tree-sitter',
  spawnargs: [ 'build-wasm', 'node_modules/tree-sitter-go' ]
}

Failed to build wasm for cpp: Command failed: node_modules/.bin/tree-sitter build-wasm node_modules/tree-sitter-cpp
events.js:298
      throw er; // Unhandled 'error' event
      ^

Error: spawn /Users/bitbegin/Desktop/syntax-highlighter/node_modules/tree-sitter-cli/tree-sitter EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -13,
  code: 'EACCES',
  syscall: 'spawn /Users/bitbegin/Desktop/syntax-highlighter/node_modules/tree-sitter-cli/tree-sitter',
  path: '/Users/bitbegin/Desktop/syntax-highlighter/node_modules/tree-sitter-cli/tree-sitter',
  spawnargs: [ 'build-wasm', 'node_modules/tree-sitter-cpp' ]
}

Failed to build wasm for c: Command failed: node_modules/.bin/tree-sitter build-wasm node_modules/tree-sitter-c
events.js:298
      throw er; // Unhandled 'error' event
      ^

Error: spawn /Users/bitbegin/Desktop/syntax-highlighter/node_modules/tree-sitter-cli/tree-sitter EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -13,
  code: 'EACCES',
  syscall: 'spawn /Users/bitbegin/Desktop/syntax-highlighter/node_modules/tree-sitter-cli/tree-sitter',
  path: '/Users/bitbegin/Desktop/syntax-highlighter/node_modules/tree-sitter-cli/tree-sitter',
  spawnargs: [ 'build-wasm', 'node_modules/tree-sitter-c' ]
}

Failed to build wasm for php: Command failed: node_modules/.bin/tree-sitter build-wasm node_modules/tree-sitter-php
events.js:298
      throw er; // Unhandled 'error' event
      ^

Error: spawn /Users/bitbegin/Desktop/syntax-highlighter/node_modules/tree-sitter-cli/tree-sitter EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -13,
  code: 'EACCES',
  syscall: 'spawn /Users/bitbegin/Desktop/syntax-highlighter/node_modules/tree-sitter-cli/tree-sitter',
  path: '/Users/bitbegin/Desktop/syntax-highlighter/node_modules/tree-sitter-cli/tree-sitter',
  spawnargs: [ 'build-wasm', 'node_modules/tree-sitter-php' ]
}

Failed to build wasm for shellscript: Command failed: node_modules/.bin/tree-sitter build-wasm node_modules/tree-sitter-bash
events.js:298
      throw er; // Unhandled 'error' event
      ^

Error: spawn /Users/bitbegin/Desktop/syntax-highlighter/node_modules/tree-sitter-cli/tree-sitter EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -13,
  code: 'EACCES',
  syscall: 'spawn /Users/bitbegin/Desktop/syntax-highlighter/node_modules/tree-sitter-cli/tree-sitter',
  path: '/Users/bitbegin/Desktop/syntax-highlighter/node_modules/tree-sitter-cli/tree-sitter',
  spawnargs: [ 'build-wasm', 'node_modules/tree-sitter-bash' ]
}

Failed to build wasm for typescript: Command failed: node_modules/.bin/tree-sitter build-wasm node_modules/tree-sitter-typescript/typescript
events.js:298
      throw er; // Unhandled 'error' event
      ^

Error: spawn /Users/bitbegin/Desktop/syntax-highlighter/node_modules/tree-sitter-cli/tree-sitter EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -13,
  code: 'EACCES',
  syscall: 'spawn /Users/bitbegin/Desktop/syntax-highlighter/node_modules/tree-sitter-cli/tree-sitter',
  path: '/Users/bitbegin/Desktop/syntax-highlighter/node_modules/tree-sitter-cli/tree-sitter',
  spawnargs: [ 'build-wasm', 'node_modules/tree-sitter-typescript/typescript' ]
}

Failed to build wasm for rust: Command failed: node_modules/.bin/tree-sitter build-wasm node_modules/tree-sitter-rust
events.js:298
      throw er; // Unhandled 'error' event
      ^

Error: spawn /Users/bitbegin/Desktop/syntax-highlighter/node_modules/tree-sitter-cli/tree-sitter EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -13,
  code: 'EACCES',
  syscall: 'spawn /Users/bitbegin/Desktop/syntax-highlighter/node_modules/tree-sitter-cli/tree-sitter',
  path: '/Users/bitbegin/Desktop/syntax-highlighter/node_modules/tree-sitter-cli/tree-sitter',
  spawnargs: [ 'build-wasm', 'node_modules/tree-sitter-rust' ]
}

Failed to build wasm for typescriptreact: Command failed: node_modules/.bin/tree-sitter build-wasm node_modules/tree-sitter-typescript/tsx
events.js:298
      throw er; // Unhandled 'error' event
      ^

Error: spawn /Users/bitbegin/Desktop/syntax-highlighter/node_modules/tree-sitter-cli/tree-sitter EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -13,
  code: 'EACCES',
  syscall: 'spawn /Users/bitbegin/Desktop/syntax-highlighter/node_modules/tree-sitter-cli/tree-sitter',
  path: '/Users/bitbegin/Desktop/syntax-highlighter/node_modules/tree-sitter-cli/tree-sitter',
  spawnargs: [ 'build-wasm', 'node_modules/tree-sitter-typescript/tsx' ]
}

audited 610 packages in 3.455s
found 0 vulnerabilities
```

**Comment by bitbegin** [comment]
on Win10:

```
npm install --target=6.1.5 --runtime=electron --disturl=https://atom.io/download/electron                         
(node:18636) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.

> syntax-highlighter@0.4.2 postinstall D:\vscode-ext\syntax-highlighter
> node ./scripts/build.js

Compiling c parser
Compiling cpp parser
Compiling go parser
Compiling javascript parser
Compiling lua parser
Compiling php parser
Compiling python parser
Compiling ruby parser
Compiling rust parser
Compiling shellscript parser
Compiling typescript parser
Compiling typescriptreact parser
Failed to build wasm for typescript: Command failed: node_modules/.bin/tree-sitter build-wasm node_modules\tree-sitter-typescript\typescript
'node_modules' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

Failed to build wasm for shellscript: Command failed: node_modules/.bin/tree-sitter build-wasm node_modules\tree-sitter-bash
'node_modules' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

Failed to build wasm for rust: Command failed: node_modules/.bin/tree-sitter build-wasm node_modules/tree-sitter-rust
'node_modules' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

Failed to build wasm for ruby: Command failed: node_modules/.bin/tree-sitter build-wasm node_modules/tree-sitter-ruby
'node_modules' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

Failed to build wasm for python: Command failed: node_modules/.bin/tree-sitter build-wasm node_modules/tree-sitter-python
'node_modules' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

Failed to build wasm for php: Command failed: node_modules/.bin/tree-sitter build-wasm node_modules/tree-sitter-php
'node_modules' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

Failed to build wasm for lua: Command failed: node_modules/.bin/tree-sitter build-wasm node_modules/tree-sitter-lua
'node_modules' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

Failed to build wasm for javascript: Command failed: node_modules/.bin/tree-sitter build-wasm node_modules/tree-sitter-javascript
'node_modules' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

Failed to build wasm for go: Command failed: node_modules/.bin/tree-sitter build-wasm node_modules/tree-sitter-go
'node_modules' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

Failed to build wasm for cpp: Command failed: node_modules/.bin/tree-sitter build-wasm node_modules/tree-sitter-cpp
'node_modules' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

Failed to build wasm for c: Command failed: node_modules/.bin/tree-sitter build-wasm node_modules/tree-sitter-c
'node_modules' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

Failed to build wasm for typescriptreact: Command failed: node_modules/.bin/tree-sitter build-wasm node_modules\tree-sitter-typescript\tsx
'node_modules' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

audited 610 packages in 5.046s
found 0 vulnerabilities
```

**Comment by EvgeniyPeshkov** [comment]
Hello @bitbegin .
Sorry for this inconvenience. Build instructions are in fact outdate.
I don't use native modules anymore. They are replaced by .wasm implementation.
So to build extension from sources you need to **install Emscripten SDK**.
Parsers will be built by postinstall hook when you call `npm install` as usual.
Please, refere to updated [BUILD.md](https://github.com/EvgeniyPeshkov/syntax-highlighter/blob/master/BUILD.md) for more details.

**Comment by EvgeniyPeshkov** [comment]
Please, reopen the issue if you'll still experience problems with build.
